version: '2.2'

services:
  mysql:
    image: jumpserver/mysql:5
    container_name: jms_mysql
    restart: always
    command: --character-set-server=utf8 --collation-server=utf8_bin
    env_file:
      - .env
    volumes:
      - ./data/mysql/my.cnf:/etc/mysql/my.cnf
      - ./data/mysql/data:/var/lib/mysql
    networks:
      - net

  core:
    image: jumpserver/core:${VERSION}
    container_name: jms_core
    restart: always
    tty: true
    command: start web
    env_file:
      - .env
    volumes:
      - ${CONFIG_DIR}/core/config.yml:/opt/jumpserver/config.yml
      - ${VOLUME_DIR}/core/data:/opt/jumpserver/data
      - ${VOLUME_DIR}/core/logs:/opt/jumpserver/logs
    networks:
      - net

  luna:
    image: jumpserver/luna:${VERSION}
    container_name: jms_luna
    restart: always
    depends_on:
      - core
    networks:
      - net

  lina:
    image: jumpserver/lina:${VERSION}
    container_name: jms_lina
    restart: always
    depends_on:
      - core
    networks:
      - net

  guacamole:
    image: jumpserver/guacamole:${VERSION}
    container_name: jms_guacamole
    env_file:
      - .env
    restart: always
    volumes:
      - ${VOLUME_DIR}/guacamole/data:/config/guacamole/data
    depends_on:
      - core
    networks:
      - net


  nginx:
    image: jumpserver/nginx:alpine2
    container_name: jms_nginx
    restart: always
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - ./config_static/http_server.conf:/etc/nginx/conf.d/default.conf
      - ${CONFIG_DIR}/nginx/cert:/etc/nginx/cert
      - ${VOLUME_DIR}/core/data:/data
      - ${VOLUME_DIR}/nginx/log:/var/log/nginx
    depends_on:
      - core
      - koko
      - guacamole
    networks:
      - net

  koko:
    image: jumpserver/koko:${VERSION}
    container_name: jms_koko
    restart: always
    tty: true
    env_file:
      - .env
    ports:
      - ${SSH_PORT}:2222
    depends_on:
      - core
    volumes:
      - ${CONFIG_DIR}/koko/config.yml:/opt/koko/config.yml
      - ${VOLUME_DIR}/koko/data:/opt/koko/data
    privileged: true
    networks:
      - net

  redis:
    image: jumpserver/redis:6-alpine
    container_name: jms_redis
    restart: always
    volumes:
      - ${VOLUME_DIR}/redis/data:/data
      - ${CONFIG_DIR}/redis/redis.conf:/etc/redis.conf
    command: ["redis-server", "/etc/redis.conf", "--requirepass", "$REDIS_PASSWORD"]
    env_file:
      - .env 
    networks:
      - net


  celery:
    image: jumpserver/core:${VERSION}
    container_name: jms_celery
    restart: always
    tty: true
    command: start task
    depends_on:
      - core
    env_file:
      - .env
    environment:
      - SERVER_HOSTNAME=${HOSTNAME}
    volumes:
      - ${VOLUME_DIR}/core/data:/opt/jumpserver/data
      - ${VOLUME_DIR}/core/logs:/opt/jumpserver/logs
    networks:
      - net

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET}
